Repository ntumlgroup/LibMultiLabel, pull requests merged in 2024-12, with the labels that each got.

#4 Update links in LibMultiLabel webpage
  docs/cli/flags.rst
  docs/cli/ov_data_format.rst
  docs/tutorials/Parameter_Selection_for_Neural_Networks.rst
Labels: documentation

#6 Remove cited paper section on the left panel
  docs/index.rst
Labels: documentation

#1 Fix two issues in linear tree-based model:
  libmultilabel/linear/tree.py
Labels: model/linear

#7 Fix bugs in latest version of NumPy
  libmultilabel/linear/tree.py
Labels: bug, model/linear, code format

#8 [Hotfix] Set scipy version to < 1.14.0
  requirements.txt
  setup.cfg
Labels: bug, package versions, release
