Repository ntumlgroup/LibMultiLabel, pull requests merged in 2025-07, with the labels that each got.

#15 Add psutil dependency to install requires
  setup.cfg
Labels: bug, model/linear, release

#20 Upgrade minimum python version from 3.8 to 3.10
  .github/workflows/basic_test.yml
  .github/workflows/python-publish.yml
  README.md
  docs/cli/nn.rst
  docs/cli/ov_data_format.rst
  docs/readme
  libmultilabel/linear/linear.py
  requirements.txt
  requirements_nn.txt
  setup.cfg
Labels: documentation, package versions, release

#22 Remove torchtext
  README.md
  docs/cli/nn.rst
  docs/examples/plot_KimCNN_quickstart.py
  libmultilabel/nn/attentionxml.py
  libmultilabel/nn/data_utils.py
  libmultilabel/nn/model.py
  libmultilabel/nn/nn_utils.py
  main.py
  requirements_nn.txt
  search_params.py
  setup.cfg
  tests/nn/components.py
  torch_trainer.py
Labels: enhancement, model/nn, package versions
